### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429

### ISSUE THREAD

**Issue by timho102003** [nperraud/download-celebA-HQ#1]
As in the title, can't get the data thru codes
>>> urllib.error.HTTPError: HTTP Error 429: Too Many Requests

Looking forward to ur response!

**Comment by nperraud** [comment]
Can you give me a bit more information?
Which script does not work? Which line? Maybe copy the full trace?

**Comment by timho102003** [comment]
Thanks for ur prompt answer!!
Downloading https://www.dropbox.com/sh/8oqt9vytwxb3s4r/AADIKlz8PR9zr6Y20qbkunrba/Img/img_align_celeba.zip?dl=1
Traceback (most recent call last):
  File "download_celebA.py", line 183, in <module>
    download_celabA(dataset_dir)
  File "download_celebA.py", line 115, in download_celabA
    filepath = download(url, dataset_dir)
  File "download_celebA.py", line 39, in download
    urlretrieve(url, filepath)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by nperraud** [comment]
I was able to reproduce the error.

The problem comes from the fact that the source of the dataset celebA has limited its access. See the link below.

https://www.dropbox.com/sh/8oqt9vytwxb3s4r/AADIKlz8PR9zr6Y20qbkunrba/Img/img_align_celeba.zip

I can fix this error if you find another place on the web to download the file `img_align_celeba.zip`.

Sorry...

**Comment by nperraud** [comment]
By the way, I think that dropbox limit download per day. So if this error happens, you should just retry the next morning...

**Comment by timho102003** [comment]
@nperraud  Actually I've download both celebA and CelebA HQ data manually. Is it possible to run the code to generate the CelebA HQ database?

**Comment by nperraud** [comment]
You can probably only run the last script `make_HQ_images.py`. But you need to have the correct folder structure for it to work. I guess if you try a bit, you will figure it out.
Good luck!
