### ISSUE TITLE
Error in make_HQ_images.py OSError: 3145728 requested and 1671040 written

### ISSUE THREAD

**Issue by TianaCo** [nperraud/download-celebA-HQ#10]
Script was working until this error:

Traceback (most recent call last):                                                                                                     
File "/workspace/make_HQ_images.py", line 164, in <module>                                                                             pool.map(do_the_work, list(range(expected_dat)))                                                                                   
File "/opt/conda/lib/python3.5/multiprocessing/pool.py", line 266, in map                                                              return self._map_async(func, iterable, mapstar, chunksize).get()                                                                   File "/opt/conda/lib/python3.5/multiprocessing/pool.py", line 644, in get                                                              raise self._value                                                                                                                
OSError: 3145728 requested and 1671040 written

**Comment by VictorZuanazzi** [comment]
I get an error in the line just above it

```
ubuntu@ip-172-31-32-19:~/GAN-ZOO/datasets/download-celebA-HQ$ python make_HQ_images.py ./CelebAHD
Loading CelebA from ./CelebAHD/celebA/Img/img_celeba
Loading CelebA-HQ deltas from ./CelebAHD/celebA-HQ
Starting a pool with 3 workers
Traceback (most recent call last):
  File "make_HQ_images.py", line 163, in <module>
    with mp.Pool(processes=num_workers) as pool:
AttributeError: __exit__
```

**Comment by nperraud** [comment]
I am sorry. I have no clue what is the problem. However, I suggest replacing the pool with a for loop. You will get a better error message. Maybe I will be able to help you then...

**Comment by nperraud** [comment]
Without any answer from you, I will close the issue.
