### ISSUE TITLE
Only Linux and Mac OS X support .7z

### ISSUE THREAD

**Issue by DenisDiachkov** [nperraud/download-celebA-HQ#18]
I've got the following exception during the downloading

` if os.name != 'posix':`
` raise NotImplementedError('Only Linux and Mac OS X support .7z '`

It downloads and unpacks the first 200K images easily but when it comes to archives like
`img_celeba.7z.001` it raises the exception.

What should I do with Windows 10 then? 7z is already installed.

**Comment by nperraud** [comment]
@realArtichoke What if you just comment these two lines?

**Comment by DenisDiachkov** [comment]
Then I have the following 
`Traceback (most recent call last):`
  `File "download_celebA.py", line 219, in <module>`
    `download_celabA(dataset_dir)`
  `File "download_celebA.py", line 203, in download_celabA`
    `archive_extract(filepath, os.path.join(dataset_dir, 'Img'))`
  `File "download_celebA.py", line 77, in archive_extract`
   ` 'Archive file extraction failed for {}.'.format(filepath))`
`RuntimeError: Archive file extraction failed for ./celebA\img_celeba.7z.001.`
