### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by JL321** [nperraud/download-celebA-HQ#19]
The above exception was raised in running download_celebA_HQ.py

Command:

python download_celebA_HQ.py ./img_align_celeba

Output log:

Deal with file: deltas00000.zip
[*] ./img_align_celeba/deltas00000.zip already exists
Traceback (most recent call last):
  File "download_celebA_HQ.py", line 93, in <module>
    with zipfile.ZipFile(save_path) as zf:
  File "/u/jliang/anaconda3/envs/tf_gpu/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/u/jliang/anaconda3/envs/tf_gpu/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Given that this issue hasn't seemed to occur previously, is this an issue associated with the file itself? Or is it due to my setup?

**Comment by mrgloom** [comment]
Seems something broken in `download_file_from_google_drive`  downloaded `deltas00000.zip` is only 4K

**Comment by nperraud** [comment]
This code worked for a while, but last time I tried it, like 2 months ago, I wasn't able to run it, even with some effort... If you succeed in fixing it, It would serve the community.

Sorry to not be more helpful

**Comment by kouohhashi** [comment]
@JL321 
I have the  same problem.
Have you solved the problem?
