### ISSUE TITLE
download_celebA.py: Checksum doesn't match

### ISSUE THREAD

**Issue by madaanpulkit** [nperraud/download-celebA-HQ#20]
Command:
`cd download-celebA-HQ/ && python download_celebA.py ./`

Output:

Downloading img_align_celeba.zip to ./celebA/img_align_celeba.zip
./celebA/img_align_celeba.zip: 1.00B [00:00, 847B/s]
Done!
Check SHA1 ./celebA/img_align_celeba.zip
Traceback (most recent call last):
  File "download_celebA.py", line 219, in <module>
    download_celabA(dataset_dir)
  File "download_celebA.py", line 183, in download_celabA
    filepaths = download_and_check(_ALIGNED_IMGS_DRIVE, dataset_dir)
  File "download_celebA.py", line 106, in download_and_check
    raise RuntimeError('Checksum mismatch for %s.' % save_path)
RuntimeError: Checksum mismatch for ./celebA/img_align_celeba.zip.

**Comment by andvalenzuela** [comment]
Same issue

**Comment by nperraud** [comment]
Clearly the download of the file  img_align_celeba.zip failled!

**Comment by eileenlcb** [comment]
the same

**Comment by jasuriy** [comment]
did you guys fix the issue ?
